<?php
global $default_allowedtags, $full_allowedtags;
$default_allowedtags = array(
'a',
'abbr',
'acronym',
'b',
'big',
'blockquote',
'br',
'caption',
'cite',
'code',
'del',
'div',
'dl',
'dt',
'dd',
'em',
'font',
'hr',
'i',
'img',
'li',
'p',
'pre',
'small',
'span',
'strike',
'strong',
'sub',
'sup',
'table',
'thead',
'tbody',
'tfoot',
'td',
'th',
'tr',
'u',
'ul',
'ol',
);



$full_allowedtags = array(
'address' => array(),
'a' => array(
	'class' => array (),
	'href' => array (),
	'id' => array (),
	'title' => array (),
	'rel' => array (),
	'rev' => array (),
	'name' => array (),
	'target' => array()),
'abbr' => array(
	'class' => array (),
	'title' => array ()),
'acronym' => array(
	'title' => array ()),
'b' => array(),
'big' => array(),
'blockquote' => array(
	'id' => array (),
	'cite' => array (),
	'class' => array(),
	'lang' => array()),
'br' => array (
	'class' => array ()),
'caption' => array(
	'align' => array (),
	'class' => array ()),
'cite' => array (
	'class' => array(),
	'dir' => array(),
	'lang' => array(),
	'title' => array ()),
'code' => array (
	'style' => array()),
'del' => array(
	'datetime' => array ()),
'dd' => array(),
'div' => array(
	'align' => array (),
	'class' => array (),
	'dir' => array (),
	'lang' => array(),
	'style' => array ()),
'dl' => array(),
'dt' => array(),
'em' => array(),
'fieldset' => array(),
'font' => array(
	'color' => array (),
	'face' => array (),
	'size' => array ()),
'h1' => array(
	'align' => array (),
	'class' => array (),
	'id'    => array (),
	'style' => array ()),
'h2' => array (
	'align' => array (),
	'class' => array (),
	'id'    => array (),
	'style' => array ()),
'h3' => array (
	'align' => array (),
	'class' => array (),
	'id'    => array (),
	'style' => array ()),
'h4' => array (
	'align' => array (),
	'class' => array (),
	'id'    => array (),
	'style' => array ()),
'h5' => array (
	'align' => array (),
	'class' => array (),
	'id'    => array (),
	'style' => array ()),
'h6' => array (
	'align' => array (),
	'class' => array (),
	'id'    => array (),
	'style' => array ()),
'hr' => array (
	'align' => array (),
	'class' => array (),
	'noshade' => array (),
	'size' => array (),
	'width' => array ()),
'i' => array(),
'img' => array(
	'alt' => array (),
	'align' => array (),
	'border' => array (),
	'class' => array (),
	'height' => array (),
	'hspace' => array (),
	'longdesc' => array (),
	'vspace' => array (),
	'src' => array (),
	'style' => array (),
	'width' => array ()),
'ins' => array(
	'datetime' => array (),
	'cite' => array ()),
'kbd' => array(),
'label' => array(
	'for' => array ()),
'legend' => array(
	'align' => array ()),
'li' => array (
	'align' => array (),
	'class' => array ()),
'p' => array(
	'class' => array (),
	'align' => array (),
	'dir' => array(),
	'lang' => array(),
	'style' => array ()),
'pre' => array(
	'style' => array(),
	'width' => array ()),
'q' => array(
	'cite' => array ()),
's' => array(),
'small' => array(),
'span' => array (
	'class' => array (),
	'dir' => array (),
	'align' => array (),
	'lang' => array (),
	'style' => array (),
	'title' => array ()),
'strike' => array(),
'strong' => array(),
'sub' => array(),
'sup' => array(),
'table' => array(
	'align' => array (),
	'bgcolor' => array (),
	'border' => array (),
	'cellpadding' => array (),
	'cellspacing' => array (),
	'class' => array (),
	'dir' => array(),
	'id' => array(),
	'rules' => array (),
	'style' => array (),
	'summary' => array (),
	'width' => array ()),
'tbody' => array(
	'align' => array (),
	'char' => array (),
	'charoff' => array (),
	'valign' => array ()),
'td' => array(
	'abbr' => array (),
	'align' => array (),
	'axis' => array (),
	'bgcolor' => array (),
	'char' => array (),
	'charoff' => array (),
	'class' => array (),
	'colspan' => array (),
	'dir' => array(),
	'headers' => array (),
	'height' => array (),
	'nowrap' => array (),
	'rowspan' => array (),
	'scope' => array (),
	'style' => array (),
	'valign' => array (),
	'width' => array ()),
'tfoot' => array(
	'align' => array (),
	'char' => array (),
	'class' => array (),
	'charoff' => array (),
	'valign' => array ()),
'th' => array(
	'abbr' => array (),
	'align' => array (),
	'axis' => array (),
	'bgcolor' => array (),
	'char' => array (),
	'charoff' => array (),
	'class' => array (),
	'colspan' => array (),
	'headers' => array (),
	'height' => array (),
	'nowrap' => array (),
	'rowspan' => array (),
	'scope' => array (),
	'valign' => array (),
	'width' => array ()),
'thead' => array(
	'align' => array (),
	'char' => array (),
	'charoff' => array (),
	'class' => array (),
	'valign' => array ()),
'tr' => array(
	'align' => array (),
	'bgcolor' => array (),
	'char' => array (),
	'charoff' => array (),
	'class' => array (),
	'style' => array (),
	'valign' => array ()),
'tt' => array(),
'u' => array(),
'ul' => array (
	'class' => array (),
	'style' => array (),
	'type' => array ()),
'ol' => array (
	'class' => array (),
	'start' => array (),
	'style' => array (),
	'type' => array ()),
'var' => array (),
'applet' => array(
	'id' => array (),
	'alt' => array (),
	'archive' => array (),
	'codebase' => array (),
	'width' => array (),
	'height' => array (),
	'name' => array (),
),
'iframe' => array(
	'class' => array (),
	'frameborder' => array (),
	'height' => array (),
	'id' => array (),
	'marginheight' => array (),
	'marginwidth' => array (),
	'name' => array (),
	'scrolling' => array (),
	'src' => array (),
	'style' => array (),
	'title' => array (),
	'width' => array (),
),
'object' => array(
	'classid' => array (),
	'width' => array (),
	'height' => array (),
	'codebase' => array (),
	'id' => array (),
),
'embed' => array(
	'type' => array (),
	'width' => array (),
	'height' => array (),
	'src' => array (),
	'flashvar' => array (),
	'allowscriptaccess' => array (),
	'allowfullscreen' => array (),
),
'param' => array(
	'name' => array (),
	'value' => array (),
),
);




