<?php 

/* 
   WARNING! DO NOT EDIT THIS FILE!

   BizzThemes framewrok is built with hooks, which are all located in
   library/hooks template directory. Please edit those files to
   customize your design/look, combined with Theme Option Panel 
   in Wordpress backed.

*/

    get_header(); 
	
    /* 
	    This is INDEX page displayed according to your settings in
	    theme options panel. You have option to show checked function
       	block sections in order you like of course - now GO TO 
		THEME OPTIONS PANEL TO SET IT UP.
	*/
		
	if ( is_front_page() ) { # regular home page
	
		foreach ($GLOBALS['opt']['bizzthemes_index_s'] as $key => $value) {
			if ( isset($GLOBALS['opt']['bizzthemes_index_s_'.$key.'']) ) {
				eval('bizz_'.$key.'(); ');
			}
		}
	
	}
	else { # blog template (static)
		
		foreach ($GLOBALS['opt']['bizzthemes_archive_s'] as $key => $value) {
			if ( isset($GLOBALS['opt']['bizzthemes_archive_s_'.$key.'']) ) {
				if ($key == 'archive') { $key = 'blog'; } // transform 'archive' -> 'blog'
				eval('bizz_'.$key.'(); ');
			}
		}
	
	}

    get_footer(); 

